name: Deploy Python Code to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Deploy to EC2
        uses: actions/ssh-key-action@v1
        with:
          host: 54.169.58.53
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd /home/ubuntu/python-addition
            python addition.py
